# Generated by Django 5.2.6 on 2026-06-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='codolio_url',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='github_url',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='linkedin_url',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='portfolio_url',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='application',
            name='resume_link',
            field=models.URLField(default='https://resumeexample.com'),
            preserve_default=False,
        ),
    ]
