# Generated by Django 5.2.6 on 2026-06-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0002_application_codolio_url_application_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
