# Generated by Django 5.2.6 on 2026-06-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobposting', '0003_application_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='email',
            field=models.EmailField(default='manas@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
