# Generated by Django 5.2.6 on 2026-06-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
