# Generated by Django 5.2.6 on 2026-06-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0002_recruiterprofile_location'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recruiterprofile',
            constraint=models.UniqueConstraint(fields=('company_name', 'location'), name='unique_company_location'),
        ),
    ]
