# Generated by Django 5.2.6 on 2026-06-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0003_recruiterprofile_unique_company_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='codolio_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
