# Generated by Django 5.2.6 on 2026-06-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0004_candidateprofile_codolio_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='phone_number',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
