# Generated by Django 5.2.6 on 2026-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0006_skill_candidateprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, to='CreateUser.skill'),
        ),
    ]
