# Generated by Django 5.2.6 on 2026-06-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateUser', '0006_skill_candidateprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='untitled resume', max_length=20)),
                ('public', models.BooleanField(default=False)),
                ('template', models.CharField(choices=[('classic', 'Classic'), ('modern', 'Modern'), ('minimal', 'Minimal')], default='classic', max_length=20)),
                ('accent_color', models.CharField(default='#3B82F6', max_length=20)),
                ('professional_summary', models.TextField(default='')),
                ('dsa_summary', models.TextField(default='')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='CreateUser.candidateprofile')),
            ],
        ),
    ]
