# Generated by Django 5.2.6 on 2026-07-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CreateUser', '0007_alter_project_tech_stack'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumedetails',
            name='included_educations',
            field=models.ManyToManyField(blank=True, to='CreateUser.education'),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='included_experiences',
            field=models.ManyToManyField(blank=True, to='CreateUser.experience'),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='included_projects',
            field=models.ManyToManyField(blank=True, to='CreateUser.project'),
        ),
        migrations.AddField(
            model_name='resumedetails',
            name='included_skills',
            field=models.ManyToManyField(blank=True, to='CreateUser.skill'),
        ),
    ]
