# Generated by Django 5.2.6 on 2026-06-22 18:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CreateUser', '0003_recruiterprofile_unique_company_location'),
        ('jobposting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField()),
                ('match_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('technical_questions', models.JSONField(default=list)),
                ('behavioral_questions', models.JSONField(default=list)),
                ('skill_gaps', models.JSONField(default=list)),
                ('preparation_plan', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='CreateUser.candidateprofile')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='jobposting.job')),
            ],
        ),
    ]
